from ownbox.manifest import Manifest
from ownbox.store import Catalog, create_launcher


def tool(name, description, tags=()):
    return Manifest(name=name, description=description, repo=f"me/{name}", tags=tags)


def test_catalog_searches_names_descriptions_and_tags():
    catalog = Catalog(
        "me",
        [tool("camera", "Take a photo", ("raspberry-pi",)), tool("notes", "Write things")],
        "now",
    )
    assert [item.name for item in catalog.find("photo")] == ["camera"]
    assert [item.name for item in catalog.find("raspberry")] == ["camera"]
    assert [item.name for item in catalog.find("camera")] == ["camera"]


def test_catalog_round_trip(tmp_path, monkeypatch):
    monkeypatch.setenv("XDG_CACHE_HOME", str(tmp_path))
    catalog = Catalog("me", [tool("demo", "Demo")], "now")
    catalog.save()
    loaded = Catalog.load()
    assert loaded is not None
    assert loaded.owner == "me"
    assert loaded.tools[0].name == "demo"


def test_launcher_routes_through_ownbox(tmp_path, monkeypatch):
    monkeypatch.setenv("OWNBOX_BIN_DIR", str(tmp_path))
    launcher = create_launcher("demo")
    assert launcher.read_text() == '#!/bin/sh\n# generated by ownbox\nexec ownbox \'demo\' "$@"\n'
    assert launcher.stat().st_mode & 0o111
