from __future__ import annotations

import json
import os
import platform
import shutil
import subprocess
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from .manifest import Manifest


def data_home() -> Path:
    return Path(os.environ.get("XDG_DATA_HOME", Path.home() / ".local/share")) / "ownbox"


def cache_home() -> Path:
    return Path(os.environ.get("XDG_CACHE_HOME", Path.home() / ".cache")) / "ownbox"


def config_home() -> Path:
    return Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "ownbox"


def bin_home() -> Path:
    return Path(os.environ.get("OWNBOX_BIN_DIR", Path.home() / ".local/bin"))


@dataclass
class Catalog:
    owner: str
    tools: list[Manifest]
    synced_at: str

    @classmethod
    def load(cls) -> Catalog | None:
        path = cache_home() / "catalog.json"
        if not path.exists():
            return None
        data = json.loads(path.read_text(encoding="utf-8"))
        return cls(
            owner=data["owner"],
            tools=[Manifest.from_dict(item, item["repo"]) for item in data["tools"]],
            synced_at=data["synced_at"],
        )

    def save(self) -> None:
        path = cache_home() / "catalog.json"
        path.parent.mkdir(parents=True, exist_ok=True)
        payload = {
            "owner": self.owner,
            "synced_at": self.synced_at,
            "tools": [tool.to_dict() for tool in self.tools],
        }
        path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    def find(self, query: str) -> list[Manifest]:
        terms = query.casefold().split()

        def score(tool: Manifest) -> tuple[int, str]:
            name = tool.name.casefold()
            haystack = " ".join((tool.name, tool.description, *tool.tags)).casefold()
            points = sum(8 if term == name else 4 if term in name else 1 for term in terms)
            if not all(term in haystack for term in terms):
                points = -1
            return (-points, name)

        return sorted((tool for tool in self.tools if score(tool)[0] < 0), key=score)

    def get(self, name: str) -> Manifest:
        matches = [tool for tool in self.tools if tool.name.casefold() == name.casefold()]
        if not matches:
            raise KeyError(name)
        return matches[0]


def new_catalog(owner: str, tools: list[Manifest]) -> Catalog:
    return Catalog(owner, tools, datetime.now(timezone.utc).isoformat())


def installations() -> dict[str, dict]:
    path = data_home() / "installed.json"
    if not path.exists():
        return {}
    return json.loads(path.read_text(encoding="utf-8"))


def save_installations(state: dict[str, dict]) -> None:
    path = data_home() / "installed.json"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(state, indent=2) + "\n", encoding="utf-8")


def launcher_path(name: str) -> Path:
    return bin_home() / name


def check_launcher(name: str) -> Path:
    path = launcher_path(name)
    if path.exists() and "# generated by ownbox" not in path.read_text(
        encoding="utf-8", errors="ignore"
    ):
        raise RuntimeError(f"refusing to replace existing command: {path}")
    return path


def create_launcher(name: str) -> Path:
    path = launcher_path(name)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f'#!/bin/sh\n# generated by ownbox\nexec ownbox {name!r} "$@"\n', encoding="utf-8"
    )
    path.chmod(0o755)
    return path


def install(tool: Manifest, destination: Path | None = None) -> Path:
    current_platform = {"linux": "linux", "darwin": "darwin", "windows": "windows"}.get(
        platform.system().casefold(), platform.system().casefold()
    )
    if tool.platforms and current_platform not in [item.casefold() for item in tool.platforms]:
        raise RuntimeError(f"{tool.name} does not support {current_platform}")
    launcher = check_launcher(tool.name)
    target = destination or data_home() / "tools" / tool.name
    if target.exists():
        raise RuntimeError(f"destination already exists: {target}")
    target.parent.mkdir(parents=True, exist_ok=True)
    clone_url = f"https://github.com/{tool.repo}.git"
    if shutil.which("gh"):
        clone = ["gh", "repo", "clone", tool.repo, str(target)]
    else:
        clone = ["git", "clone", clone_url, str(target)]
    subprocess.run(clone, check=True)
    try:
        for command in tool.setup:
            subprocess.run(command, cwd=target, shell=True, check=True)
    except subprocess.CalledProcessError:
        raise RuntimeError(f"setup failed; checkout kept at {target}") from None
    create_launcher(tool.name)
    state = installations()
    state[tool.name] = {
        "repo": tool.repo,
        "path": str(target),
        "launcher": str(launcher),
        "installed_at": datetime.now(timezone.utc).isoformat(),
    }
    save_installations(state)
    return target


def uninstall(name: str, keep_files: bool = False) -> Path:
    state = installations()
    matches = [
        installed_name for installed_name in state if installed_name.casefold() == name.casefold()
    ]
    if not matches:
        raise RuntimeError(f"{name!r} is not installed")

    installed_name = matches[0]
    item = state[installed_name]
    target = Path(item["path"]).expanduser()
    launcher = Path(item.get("launcher", launcher_path(installed_name))).expanduser()

    if launcher.exists() and (
        not launcher.is_file()
        or "# generated by ownbox" not in launcher.read_text(encoding="utf-8", errors="ignore")
    ):
        raise RuntimeError(f"refusing to remove command not generated by Ownbox: {launcher}")

    if not keep_files and target.exists():
        resolved_target = target.resolve()
        if (
            target.is_symlink()
            or resolved_target == Path(resolved_target.anchor)
            or resolved_target == Path.home()
        ):
            raise RuntimeError(f"refusing to remove unsafe checkout path: {target}")

    if launcher.exists():
        launcher.unlink()
    if not keep_files and target.exists():
        shutil.rmtree(target)

    del state[installed_name]
    save_installations(state)
    return target


def update(name: str) -> Path:
    state = installations()
    if name not in state:
        raise KeyError(name)
    target = Path(state[name]["path"])
    subprocess.run(["git", "-C", str(target), "pull", "--ff-only"], check=True)
    manifest_path = target / "ownbox.yaml"
    if manifest_path.exists():
        manifest = Manifest.from_path(manifest_path, state[name]["repo"])
        for command in manifest.setup:
            subprocess.run(command, cwd=target, shell=True, check=True)
    create_launcher(name)
    state[name]["updated_at"] = datetime.now(timezone.utc).isoformat()
    save_installations(state)
    return target
