from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
from collections.abc import Callable
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from .manifest import Manifest, current_platform

# Network-bound git plumbing (clone/fetch/merge/rev-parse/show) gets its own budget,
# separate from arbitrary tool-authored setup/update/remove shell commands, which may
# legitimately run longer (e.g. compiling something).
CLONE_TIMEOUT = int(os.environ.get("OWNBOX_CLONE_TIMEOUT", "600"))
COMMAND_TIMEOUT = int(os.environ.get("OWNBOX_COMMAND_TIMEOUT", "1800"))


def _run(command, *, timeout: int, check: bool = False, **kwargs):
    try:
        return subprocess.run(command, timeout=timeout, check=check, **kwargs)
    except subprocess.TimeoutExpired as exc:
        raise RuntimeError(f"command timed out after {timeout}s: {command}") from exc


def _atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
        os.replace(tmp_name, path)
    except BaseException:
        try:
            os.unlink(tmp_name)
        except OSError:
            pass
        raise


def data_home() -> Path:
    if current_platform() == "windows":
        return Path(os.environ.get("LOCALAPPDATA", Path.home() / "AppData/Local")) / "ownbox"
    return Path(os.environ.get("XDG_DATA_HOME", Path.home() / ".local/share")) / "ownbox"


def cache_home() -> Path:
    if current_platform() == "windows":
        return data_home() / "cache"
    return Path(os.environ.get("XDG_CACHE_HOME", Path.home() / ".cache")) / "ownbox"


def config_home() -> Path:
    if current_platform() == "windows":
        return Path(os.environ.get("APPDATA", Path.home() / "AppData/Roaming")) / "ownbox"
    return Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "ownbox"


def bin_home() -> Path:
    if os.environ.get("OWNBOX_BIN_DIR"):
        return Path(os.environ["OWNBOX_BIN_DIR"])
    if current_platform() == "windows":
        return data_home() / "bin"
    return Path.home() / ".local/bin"


@dataclass
class Catalog:
    owner: str
    tools: list[Manifest]
    synced_at: str

    @classmethod
    def load(cls) -> Catalog | None:
        path = cache_home() / "catalog.json"
        if not path.exists():
            return None
        data = json.loads(path.read_text(encoding="utf-8"))
        return cls(
            owner=data["owner"],
            tools=[Manifest.from_dict(item, item["repo"]) for item in data["tools"]],
            synced_at=data["synced_at"],
        )

    def save(self) -> None:
        path = cache_home() / "catalog.json"
        payload = {
            "owner": self.owner,
            "synced_at": self.synced_at,
            "tools": [tool.to_dict() for tool in self.tools],
        }
        _atomic_write(path, json.dumps(payload, indent=2) + "\n")

    def find(self, query: str) -> list[Manifest]:
        terms = query.casefold().split()

        def score(tool: Manifest) -> tuple[int, str]:
            name = tool.name.casefold()
            haystack = " ".join((tool.name, tool.description, *tool.tags)).casefold()
            points = sum(8 if term == name else 4 if term in name else 1 for term in terms)
            if not all(term in haystack for term in terms):
                points = -1
            return (-points, name)

        return sorted((tool for tool in self.tools if score(tool)[0] < 0), key=score)

    def get(self, name: str) -> Manifest:
        matches = [tool for tool in self.tools if tool.name.casefold() == name.casefold()]
        if not matches:
            raise KeyError(name)
        return matches[0]


def new_catalog(owner: str, tools: list[Manifest]) -> Catalog:
    return Catalog(owner, tools, datetime.now(timezone.utc).isoformat())


def installations() -> dict[str, dict]:
    path = data_home() / "installed.json"
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise RuntimeError(f"installed.json is corrupt or truncated: {path}") from exc


def save_installations(state: dict[str, dict]) -> None:
    path = data_home() / "installed.json"
    _atomic_write(path, json.dumps(state, indent=2) + "\n")


def launcher_path(name: str) -> Path:
    suffix = ".cmd" if current_platform() == "windows" else ""
    return bin_home() / f"{name}{suffix}"


def check_launcher(name: str) -> Path:
    path = launcher_path(name)
    if (
        path.exists()
        and "generated by ownbox"
        not in path.read_text(encoding="utf-8", errors="ignore").casefold()
    ):
        raise RuntimeError(f"refusing to replace existing command: {path}")
    return path


def create_launcher(name: str) -> Path:
    path = launcher_path(name)
    path.parent.mkdir(parents=True, exist_ok=True)
    if current_platform() == "windows":
        path.write_text(
            f'@echo off\nrem generated by ownbox\nownbox "{name}" %*\nexit /b %errorlevel%\n',
            encoding="utf-8",
        )
    else:
        path.write_text(
            f'#!/bin/sh\n# generated by ownbox\nexec ownbox {name!r} "$@"\n',
            encoding="utf-8",
        )
        path.chmod(0o755)
    return path


def launcher_names(tool: Manifest) -> tuple[str, ...]:
    names = tuple(tool.entry_commands())
    return names or (tool.name,)


def create_launchers(tool: Manifest) -> dict[str, str]:
    return {name: str(create_launcher(name)) for name in launcher_names(tool)}


def installed_launcher_paths(installed_name: str, item: dict) -> dict[str, Path]:
    launchers = item.get("launchers")
    if isinstance(launchers, dict):
        return {name: Path(path).expanduser() for name, path in launchers.items()}
    return {installed_name: Path(item.get("launcher", launcher_path(installed_name))).expanduser()}


def resolve_installation(state: dict[str, dict], name: str) -> tuple[str, dict]:
    matches = []
    for installed_name, item in state.items():
        aliases = installed_launcher_paths(installed_name, item)
        if installed_name.casefold() == name.casefold() or any(
            alias.casefold() == name.casefold() for alias in aliases
        ):
            matches.append((installed_name, item))
    if not matches:
        raise RuntimeError(f"{name!r} is not installed")
    if len(matches) > 1:
        raise RuntimeError(f"command {name!r} belongs to multiple installed tools")
    return matches[0]


def git_revision(target: Path) -> str | None:
    try:
        result = _run(
            ["git", "-C", str(target), "rev-parse", "HEAD"],
            timeout=CLONE_TIMEOUT,
            check=True,
            capture_output=True,
            text=True,
        )
    except (subprocess.CalledProcessError, OSError):
        return None
    revision = result.stdout.strip()
    return revision or None


def install(
    tool: Manifest,
    destination: Path | None = None,
    approve_commands: Callable[[tuple[str, ...]], bool] | None = None,
) -> Path:
    platform_name = current_platform()
    if tool.platforms and platform_name not in [item.casefold() for item in tool.platforms]:
        raise RuntimeError(f"{tool.name} does not support {platform_name}")
    state = installations()
    occupied = {
        alias.casefold()
        for installed_name, item in state.items()
        for alias in installed_launcher_paths(installed_name, item)
    }
    for name in launcher_names(tool):
        if name.casefold() in occupied:
            raise RuntimeError(f"command is already provided by an installed tool: {name}")
        check_launcher(name)
    target = (destination or data_home() / "tools" / tool.name).expanduser().resolve()
    if target.exists():
        raise RuntimeError(f"destination already exists: {target}")
    if tool.setup and approve_commands is not None and not approve_commands(tool.setup):
        raise RuntimeError("setup commands were not approved")
    target.parent.mkdir(parents=True, exist_ok=True)
    clone_url = f"https://github.com/{tool.repo}.git"
    if shutil.which("gh"):
        clone = ["gh", "repo", "clone", tool.repo, str(target)]
    else:
        clone = ["git", "clone", clone_url, str(target)]
    _run(clone, timeout=CLONE_TIMEOUT, check=True)

    # Record the checkout before running setup so a failed setup still leaves a
    # tracked (and therefore uninstallable) entry instead of an orphaned checkout.
    state[tool.name] = {
        "repo": tool.repo,
        "path": str(target),
        "installed_at": datetime.now(timezone.utc).isoformat(),
        "revision": git_revision(target),
        "state": "incomplete",
    }
    save_installations(state)

    try:
        for command in tool.setup:
            _run(command, cwd=target, shell=True, check=True, timeout=COMMAND_TIMEOUT)
    except subprocess.CalledProcessError:
        raise RuntimeError(
            f"setup failed; checkout kept at {target} "
            f"(run 'ownbox uninstall {tool.name}' to remove it)"
        ) from None

    launchers = create_launchers(tool)
    state[tool.name]["launchers"] = launchers
    state[tool.name]["state"] = "complete"
    save_installations(state)
    return target


def uninstall(
    name: str,
    keep_files: bool = False,
    approve_commands: Callable[[tuple[str, ...]], bool] | None = None,
) -> Path:
    state = installations()
    installed_name, item = resolve_installation(state, name)
    target = Path(item["path"]).expanduser()
    launchers = installed_launcher_paths(installed_name, item)

    for launcher in launchers.values():
        if launcher.exists() and (
            not launcher.is_file()
            or "generated by ownbox"
            not in launcher.read_text(encoding="utf-8", errors="ignore").casefold()
        ):
            raise RuntimeError(f"refusing to remove command not generated by Ownbox: {launcher}")

    if not keep_files and target.exists():
        resolved_target = target.resolve()
        if (
            target.is_symlink()
            or resolved_target == Path(resolved_target.anchor)
            or resolved_target == Path.home()
        ):
            raise RuntimeError(f"refusing to remove unsafe checkout path: {target}")

    manifest_path = target / "ownbox.yaml"
    if manifest_path.exists():
        manifest = Manifest.from_path(manifest_path, item["repo"])
        if manifest.remove:
            if approve_commands is not None and not approve_commands(manifest.remove):
                raise RuntimeError("remove commands were not approved")
            for command in manifest.remove:
                _run(command, cwd=target, shell=True, check=True, timeout=COMMAND_TIMEOUT)

    for launcher in launchers.values():
        if launcher.exists():
            launcher.unlink()
    if not keep_files and target.exists():
        shutil.rmtree(target)

    del state[installed_name]
    save_installations(state)
    return target


def _read_incoming_manifest(target: Path, repo: str) -> Manifest | None:
    """Read ownbox.yaml as it will look after a fast-forward, without touching the tree.

    Prefers the fetched revision (FETCH_HEAD); falls back to whatever manifest is
    already checked out; falls back to None (no lifecycle commands) if neither exists.
    """
    try:
        result = _run(
            ["git", "-C", str(target), "show", "FETCH_HEAD:ownbox.yaml"],
            timeout=CLONE_TIMEOUT,
            check=True,
            capture_output=True,
            text=True,
        )
    except subprocess.CalledProcessError:
        manifest_path = target / "ownbox.yaml"
        if manifest_path.exists():
            return Manifest.from_path(manifest_path, repo)
        return None
    return Manifest.from_text(result.stdout, repo)


def update(
    name: str,
    approve_commands: Callable[[tuple[str, ...]], bool] | None = None,
) -> Path:
    state = installations()
    installed_name, item = resolve_installation(state, name)
    target = Path(item["path"])

    try:
        _run(["git", "-C", str(target), "fetch"], timeout=CLONE_TIMEOUT, check=True)
    except subprocess.CalledProcessError as exc:
        raise RuntimeError(f"failed to fetch updates for {installed_name}") from exc

    manifest = _read_incoming_manifest(target, item["repo"])
    commands: tuple[str, ...] = ()
    if manifest is not None:
        commands = manifest.update or manifest.setup

    if commands and approve_commands is not None and not approve_commands(commands):
        raise RuntimeError("update commands were not approved; checkout was left unchanged")

    try:
        _run(
            ["git", "-C", str(target), "merge", "--ff-only", "FETCH_HEAD"],
            timeout=CLONE_TIMEOUT,
            check=True,
        )
    except subprocess.CalledProcessError as exc:
        raise RuntimeError(f"failed to fast-forward {installed_name}") from exc

    for command in commands:
        _run(command, cwd=target, shell=True, check=True, timeout=COMMAND_TIMEOUT)

    if manifest is not None:
        old_launchers = installed_launcher_paths(installed_name, item)
        new_names = launcher_names(manifest)
        occupied = {
            alias.casefold()
            for other_name, other_item in state.items()
            if other_name != installed_name
            for alias in installed_launcher_paths(other_name, other_item)
        }
        for launcher_name in new_names:
            if launcher_name.casefold() in occupied:
                raise RuntimeError(
                    f"command is already provided by an installed tool: {launcher_name}"
                )
            check_launcher(launcher_name)
        retained = {launcher_name.casefold() for launcher_name in new_names}
        for launcher_name, launcher in old_launchers.items():
            if launcher_name.casefold() not in retained and launcher.exists():
                check_launcher(launcher_name)
                launcher.unlink()
        item["launchers"] = create_launchers(manifest)
        item.pop("launcher", None)
    else:
        create_launcher(installed_name)
    item["revision"] = git_revision(target)
    item["updated_at"] = datetime.now(timezone.utc).isoformat()
    save_installations(state)
    return target
